language: node_js
node_js:
- '6'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_URL=$(if test $TRAVIS_BRANCH = master -o $TRAVIS_BRANCH = stage; then echo "http://flux-react-example.herokuapp.com"; elif test $TRAVIS_BRANCH = test; then echo "https://flux-react-example-test.herokuapp.com"; else echo "."; fi)
  - secure: NcG3pl3uhwuhfni18QpywTHZ2pZ1dxTCSpSDNlfkdYAKKjKrocWh5vuf+HmZzT4r0XuHb4cN8/cvXTn5J4+e+NtcEP7QkN1YCbqU0towoU/KvDZEr0cW8nanbQctUEc9Fe1X9WJd/f5k0T2oXxJ5DAqnLmSJH+t8I5qijM1pQ7k=
  - secure: JmtKHcbatR/ImIJ7Hv+2sJinVFreQLR8Af83fgf9M/N+iBAFrwjhXGAxKAHkdAmn33kOG5W6FMZxrQr74+2gzOv1YxTcCxJq2EumjdjUhv0qQ0NAA1kVeVV4EYlBn8o5OPtY9Z3DyltZDlH62eMu1fsU2C+hDlNcKlHQhtDWIR8=
  - secure: HkrVzqt1o1YN2kic9VWI3Uquwdjgar8DDfHFMc5Vr09xo5naokxRU0vntQa77fHmvUloCLPB01v0vHDqP/ORRWFgGAgGZFDq71Pubp+qWgwXibFbAmNdES0vzPZhDV62gNO4AOxZlU84QNp15XtkxdpIqu00WmoqNgPtbKF5hCE=
addons:
  sauce_connect: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
- echo DEPLOY_URL=$DEPLOY_URL
- sudo apt-get update
- sudo apt-get install rubygems
- gem install compass
before_script:
- npm install -g grunt-cli@0.1.13
after_success:
- cat reports/coverage/lcov.info | ./node_modules/.bin/coveralls
before_deploy:
- npm run build
- rm -rf node_modules/
deploy:
  provider: heroku
  api_key:
    secure: LnMaWuov0LkD3H+MCmBSaIg90YBKH0Bs+1EhRzaGcU0setO+MVsfYyBQ/UCRgg9g/BvCYW+nocjajeZ+/04GbOXEitAG7gIWSdPrApf2RJHzOs/xzS2tiVnlcFXbloDIv4ChjZ0KH4254VI3vjmMcXYC3ZswJIE38dkMbVAUCnY=
  app:
    stage: flux-react-example
    master: flux-react-example
    test: flux-react-example-test
  skip_cleanup: true
  on:
    repo: localnerve/flux-react-example
    node: 6
after_deploy:
- npm install
- npm run functest -- $DEPLOY_URL
- grunt perfbudget:mobile
